spring:
  datasource:
    url: jdbc:postgresql://34.69.123.199:5432/venta_camisetas
    username: postgres
    password: 2qqnkLvPyqtBIKlB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: false
