spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/venta_camisetas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true